name: done-connector
version: '1.11.1'
main: me.suda.doneconnector.DoneConnector
api-version: '1.18'
commands:
  done:
    description: 후원 기능 상태를 변경.
    usage: /<command> [on|off|connect|reconnect|reload|add|list|autoconnect|test|ranking|stats]
  doneconnector:
    description: 인증 시스템 관리 명령어
    usage: /<command> [auth|reload|status|register|test|help]
    permission: doneconnector.admin