name: done-connector
version: '1.10.0'
main: me.suda.doneconnector.DoneConnector
api-version: '1.18'
commands:
  done:
    description: 후원 기능 상태를 변경.
    usage: /<command> [on|off|connect|reconnect|reload|add|list|autoconnect|test|ranking|stats]